// Exam 04 - Events System/frontend/src/app/components/layout-area/page-not-found/page-not-found.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-page-not-found',
	templateUrl: './page-not-found.component.html',
	styleUrls: ['./page-not-found.component.css']
})
export class PageNotFoundComponent {

	constructor() { }

}

<div class="page-not-found">
    <h1>404 - Page Not Found :(</h1>
    <p>Don’t worry, we’ll help you get where you need to go. Try searching again, or using the links below to find what
        you’re looking for:</p>

    <h4>Popular Links: </h4>

    <ul>
        <li>
            <a routerLink="/home">Home</a>
        </li>
        <li>
            <a routerLink="/events">Events</a>
        </li>
    </ul>
</div>

// Project 03 - Cool Vacation/vacations-frontend/src/Components/LayoutArea/PageNotFound/PageNotFound.tsx
import { NavLink } from "react-router-dom";
import "./PageNotFound.css";

function PageNotFound(): JSX.Element {
    return (
        <div className="PageNotFound">
			<h1>404 - Page Not Found :(</h1>
            <p>Don’t worry, we’ll help you get where you need to go. Try searching again, or using the links below to find what you’re looking for:</p>

            <h4>Popular Links: </h4>

            <ul>
                <li><NavLink to="/home">Home Page</NavLink></li>
                <li><NavLink to="/vacations">Vacations List</NavLink></li>
            </ul>
        </div>
    );
}

export default PageNotFound;
